import './lib/setup';

import '@kaname-png/plugin-subcommands-advanced/register';
import { LogLevel } from '@sapphire/framework';
import { GatewayIntentBits } from 'discord.js';
import { SapphireCustomClient } from './customClient';

const client = new SapphireCustomClient({
	defaultPrefix: '!',
	subcommandsAdvanced: {
		/* All options are optionals */
		nameCommandsAutogenerated: true
	},
	caseInsensitiveCommands: true,
	logger: {
		level: LogLevel.Debug
	},
	intents: [
		GatewayIntentBits.DirectMessages,
		GatewayIntentBits.GuildMessages,
		GatewayIntentBits.Guilds,
		GatewayIntentBits.MessageContent,
		GatewayIntentBits.GuildPresences,
		GatewayIntentBits.GuildMembers,
		GatewayIntentBits.GuildMessageReactions,
		GatewayIntentBits.GuildMessageTyping,
		GatewayIntentBits.GuildVoiceStates,
		GatewayIntentBits.GuildEmojisAndStickers,
		GatewayIntentBits.GuildInvites
	],
	loadMessageCommandListeners: true
});

const main = async (): Promise<void> => {
	try {
		client.logger.info('Logging in');
		await client.login();
		client.logger.info('logged in');
	} catch (error) {
		client.logger.fatal(error);
		await client.destroy();
		process.exit(1);
	}
};

void main();
